/**
 * Lojas importadas do Excel "Base lojas.xlsx"
 * Apenas lojas com avaliações do Google Maps foram incluídas
 * 
 * Gerado em: 2025-12-13T03:43:01.807Z
 * Total de lojas: 158
 */

import type { Loja } from '@/types';

export const lojasImportadas: Loja[] = [
  {
    id: 'loja-001',
    nome: 'Shopping RioSul',
    place_id: 'ChIJGbC2UPh_mQARaQ-EQH_-1IY',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Rua Lauro Müller, 116 - Botafogo, Rio de Janeiro - RJ, 22290-070, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-002',
    nome: 'Brasília Shopping',
    place_id: 'ChIJbVO40fs6WpMRjLuC-AD-i4E',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'SCN Quadra 05 BL A - Asa Norte, Brasília - DF, 70715-900, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-003',
    nome: 'ParkShopping',
    place_id: 'ChIJt2it6ikwWpMRzJOFvFVXmMQ',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'Saí - SIN, Brasília - DF, 71219-900, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-004',
    nome: 'Barra Shopping',
    place_id: 'ChIJtfU8L0jamwARvyjdP06T3ac',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. das Américas, 4666 - Barra da Tijuca, Rio de Janeiro - RJ, 22640-102, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-005',
    nome: 'Shopping Center Norte',
    place_id: 'ChIJU6Ztw5ZYzpQRH-wv8FA7VSc',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Otto Baumgart, 245 - Vila Guilherme, São Paulo - SP, 02049-000, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-006',
    nome: 'Pátio Brasil Shopping',
    place_id: 'ChIJF2bu_eU6WpMR_KTjG7bIuTk',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'SCS Q. 7 BL A - Asa Sul, Brasília - DF, 70307-902, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-007',
    nome: 'Shopping Parque Dom Pedro',
    place_id: 'ChIJKfyS5YPGyJQRwcEut36_P1A',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Guilherme Campos, 500 - Jardim Santa Genebra, Campinas - SP, 13080-000, Brazil',
    cidade: 'Campinas',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-008',
    nome: 'Tatuapé',
    place_id: 'ChIJvUwAiENczpQRIk-sPXPJvn0',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Melo Freire - Tatuapé, São Paulo - SP, 03314-030, Brazil',
    cidade: 'São Paulo',
    time: 'Falcões SP',
  },
  {
    id: 'loja-009',
    nome: 'BH Shopping',
    place_id: 'ChIJ9zkBafmXpgARPuHqzYAXq90',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'BR-356, 3049 - Belvedere, Belo Horizonte - MG, 30320-900, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-010',
    nome: 'Shopping SP Market',
    place_id: 'ChIJtYJGwSVQzpQRRjvMjONDiLU',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. das Nações Unidas, 22540 - Jurubatuba, São Paulo - SP, 04795-000, Brazil',
    cidade: 'São Paulo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-011',
    nome: 'Ribeirão Shopping',
    place_id: 'ChIJ41zN4zK5uZQRZa1S89tw9Dk',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Cel. Fernando Ferreira Leite, 1540 - Jardim California, Ribeirão Preto - SP, 14026-900, Brazil',
    cidade: 'Ribeirão Preto',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-012',
    nome: 'Iguatemi',
    place_id: 'ChIJ_2UYIGNJxwcRH4FygqPNdy0',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'Av. Washington Soares, 85 - Edson Queiroz, Fortaleza - CE, 60811-341, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-013',
    nome: 'Shopping Recife',
    place_id: 'ChIJy9ZoeUIfqwcRSaF2T_l9eDQ',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'R. Padre Carapuceiro, 777 - Boa Viagem, Recife - PE, 51020-900, Brazil',
    cidade: 'Recife',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-014',
    nome: 'Shopping Estação',
    place_id: 'ChIJv7RU7Wjk3JQR658Cc0Mmlk8',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Sete de Setembro, 2775 - Rebouças, Curitiba - PR, 80230-010, Brazil',
    cidade: 'Curitiba',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-015',
    nome: 'Pátio Savassi',
    place_id: 'ChIJM6R2VsWZpgAR84udKTEZUFk',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. do Contorno, 6061 - São Pedro, Belo Horizonte - MG, 30110-929, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-016',
    nome: 'Midway Mall',
    place_id: 'ChIJcb6iVfr_sgcRfOD4-UdQ8es',
    estado: 'RN',
    regiao: 'Nordeste',
    endereco: 'Av. Nevaldo Rocha, 3775 - Tirol, Natal - RN, 59015-450, Brazil',
    cidade: 'Natal',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-017',
    nome: 'SuperShopping Osasco',
    place_id: 'ChIJzaIZDmv_zpQRmY3ZPgo_Nc8',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. dos Autonomistas, 1828 - Industrial Autonomistas, Osasco - SP, 06020-010, Brazil',
    cidade: 'Osasco',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-018',
    nome: 'Shopping da Bahia',
    place_id: 'ChIJl6pJVD0bFgcRKm-2zOc3ReU',
    estado: 'BA',
    regiao: 'Nordeste',
    endereco: 'Av. Tancredo Neves, 148 - Caminho das Árvores, Salvador - BA, 41820-020, Brazil',
    cidade: 'Salvador',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-019',
    nome: 'Santa Cruz',
    place_id: 'ChIJxYfY1DNazpQRpcAmbOPOYRU',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Domingos de Morais, 2564 - Vila Mariana, São Paulo - SP, 04036-100, Brazil',
    cidade: 'São Paulo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-020',
    nome: 'Salvador Shopping',
    place_id: 'ChIJHyGsDFEWFgcRi6Q0pZcQpNU',
    estado: 'BA',
    regiao: 'Nordeste',
    endereco: 'Av. Tancredo Neves, 3133 - Caminho das Árvores, Salvador - BA, 41820-021, Brazil',
    cidade: 'Salvador',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-021',
    nome: 'Bourbon Shopping São Paulo',
    place_id: 'ChIJcwFkvOJXzpQRHtSx5FGIHXg',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Palestra Itália, 500 - Perdizes, São Paulo - SP, 05005-030, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-022',
    nome: 'ItaúPower',
    place_id: 'ChIJfSRsvuOVpgARuF1qhYcCKBg',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. General David Sarnoff, 5160 - Cidade Industrial, Contagem - MG, 32210-110, Brazil',
    cidade: 'Contagem',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-023',
    nome: 'Partage Shopping',
    place_id: 'ChIJzYBViaT3zpQR4qdH7YZnkNk',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Conselheiro Moreira de Barros, 2780 - Lauzane Paulista, São Paulo - SP, 02430-001, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-024',
    nome: 'Litoral Plaza Shopping',
    place_id: 'ChIJf9R16lMczpQRVnIk3IBz7es',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Ayrton Senna da Silva, 1511 - Xixová, Praia Grande - SP, 11726-900, Brazil',
    cidade: 'Praia Grande',
    time: 'Lobos SP',
  },
  {
    id: 'loja-025',
    nome: 'Central Plaza Shopping',
    place_id: 'ChIJCdwfvcVdzpQRuBBHGoMO16I',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dr. Francisco Mesquita, 1000 - Jardim Ibitirama, São Paulo - SP, 03153-001, Brazil',
    cidade: 'São Paulo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-026',
    nome: 'Independência Shopping',
    place_id: 'ChIJu7uqcw2bmAARrENeOu2m_7Y',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Presidente Itamar Franco, 3600 - Cascatinha, Juiz de Fora - MG, 36025-290, Brazil',
    cidade: 'Juíz de Fora',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-027',
    nome: 'Palladium Shopping Center',
    place_id: 'ChIJaX7Xj13j3JQRbOOhgR55QH4',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Pres. Kennedy, 4121 - Portão, Curitiba - PR, 80610-010, Brazil',
    cidade: 'Curitiba',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-028',
    nome: 'CenterVale Shopping',
    place_id: 'ChIJexOpXrlLzJQR9R9sLGlRlh0',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dep. Benedito Matarazzo, 9403 - Jardim Oswaldo Cruz, São José dos Campos - SP, 12215-900, Brazil',
    cidade: 'São José dos Campos',
    time: 'Falcões SP',
  },
  {
    id: 'loja-029',
    nome: 'NorteShopping RJ',
    place_id: 'ChIJ9yMkU1t9mQAR4x9nlVEeFSU',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Dom Hélder Câmara, 5474 - Cachambi, Rio de Janeiro - RJ, 20771-004, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-030',
    nome: 'Bourbon Hipermercado São Leopoldo',
    place_id: 'ChIJ8aTmW1BoGZURfKqZWWHG6_Y',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'R. Primeiro de Março, 821 - Centro, São Leopoldo - RS, 93010-210, Brazil',
    cidade: 'São Leopoldo',
    time: 'SULcesso',
  },
  {
    id: 'loja-031',
    nome: 'Shopping Bougainville',
    place_id: 'ChIJSUY36Qj0XpMRI1tbF-C1V90',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'R. 9, 1855 - St. Marista, Goiânia - GO, 74150-130, Brazil',
    cidade: 'Goiânia',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-032',
    nome: 'Neumarkt Shopping',
    place_id: 'ChIJz1mcAsMY35QRaHRhpQ_gTic',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'R. 7 de Setembro, 1213 - Centro, Blumenau - SC, 89010-911, Brazil',
    cidade: 'Blumenau',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-033',
    nome: 'Catuaí Londrina Shopping Mall',
    place_id: 'ChIJCfWlcMlc65QR_h_yMZb3gKk',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Rod. Celso Garcia Cid, 5600 - Palhano 2, Londrina - PR, 86050-901, Brazil',
    cidade: 'Londrina',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-034',
    nome: 'Brasil Park Shopping',
    place_id: 'ChIJUeuIjG-kXpMRV3wu63YSRoI',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Brasil Norte, 505 - Centro, Anápolis - GO, 75113-570, Brazil',
    cidade: 'Anápolis',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-035',
    nome: 'North Shopping Fortaleza',
    place_id: 'ChIJHXpW735JxwcRtxlKc5JMwVk',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'Av. Bezerra de Menezes, 2450 - Presidente Kennedy, Fortaleza - CE, 60325-002, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-036',
    nome: 'Via Sul Shopping',
    place_id: 'ChIJGYpFQ3tFxwcRaqpoPAH_xM4',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'Av. Washington Soares, 4335 - Sapiranga-Coité, Fortaleza - CE, 60833-005, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-037',
    nome: 'Shopping União de Osasco',
    place_id: 'ChIJs7tPvUH_zpQR1ijQqRg_iAA',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. dos Autonomistas, 1400 - Vila Yara, Osasco - SP, 06020-010, Brazil',
    cidade: 'Osasco',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-038',
    nome: 'Goiânia Shopping',
    place_id: 'ChIJs20TRCXxXpMRgx2tuyLDIBs',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'Av. T-10, 1300 - St. Bueno, Goiânia - GO, 74223-060, Brazil',
    cidade: 'Goiânia',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-039',
    nome: 'Shopping Tacaruna',
    place_id: 'ChIJjxyfc30YqwcRXfWTGZIjF0o',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'Shopping Tacaruna - Av. Gov. Agamenon Magalhães, 153 - Santo Amaro, Recife - PE, 50110-900, Brazil',
    cidade: 'Recife',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-040',
    nome: 'VillagioCaxias Shopping',
    place_id: 'ChIJPd68namjHpURL7Ees8Zdh3w',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Rodovia RSC 453, 2780 - Desvio Rizzo, Caxias do Sul - RS, 95110-900, Brazil',
    cidade: 'Caxias do Sul',
    time: 'SULcesso',
  },
  {
    id: 'loja-041',
    nome: 'Boulevard Shopping Brasília',
    place_id: 'ChIJxzxbSJI5WpMRg0uFMdQhKuc',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'Setor Terminal Norte, Conj J - Asa Norte, Brasília - DF, 70770-100, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-042',
    nome: 'Bourbon Shopping Ipiranga',
    place_id: 'ChIJUY0LxRp4GZUROy9g0y71DSg',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. Ipiranga, 5200 - Jardim Botânico, Porto Alegre - RS, 90610-000, Brazil',
    cidade: 'Porto Alegre',
    time: 'SULcesso',
  },
  {
    id: 'loja-043',
    nome: 'Taguatinga Shopping',
    place_id: 'ChIJwWC82IsyWpMRITE5cD0xgtA',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'QS 01 Rua 210 - Taguatinga, Brasília - DF, 72036-004, Brazil',
    cidade: 'Taguatinga',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-044',
    nome: 'Boulevard Shopping Belém',
    place_id: 'ChIJWROL75eOpJIRoyndGPE4LAA',
    estado: 'PA',
    regiao: 'Norte',
    endereco: 'Av. Visc. de Souza Franco, 776 - Reduto, Belém - PA, 66053-000, Brazil',
    cidade: 'Belém',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-045',
    nome: 'Ilha Plaza',
    place_id: 'ChIJW4yxOYh3mQARVQBlaMZtGXc',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Maestro Paulo e Silva, 400 - Jardim Carioca, Rio de Janeiro - RJ, 21920-445, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-046',
    nome: 'PrudenShopping',
    place_id: 'ChIJ356Dyz30k5QR3b0mxV2HOEk',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Manoel Goulart, 2400 - Jardim das Rosas, Pres. Prudente - SP, 19060-000, Brazil',
    cidade: 'Presidente Prudente',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-047',
    nome: 'Beiramar Shopping',
    place_id: 'ChIJAxMtuRY4J5URsXRWzJtSUY4',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'R. Bocaiúva, 2468 - Centro, Florianópolis - SC, 88015-902, Brazil',
    cidade: 'Florianópolis',
    time: 'SULcesso',
  },
  {
    id: 'loja-048',
    nome: 'Outlet Extrema Ponta dos Pés',
    place_id: 'ChIJz_DVTimtzpQRglU7A-BFZOU',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'R. João Mendes, 146 - Centro, Extrema - MG, 37640-000, Brazil',
    cidade: 'Extrema',
    time: 'Falcões SP',
  },
  {
    id: 'loja-049',
    nome: 'Shopping Mueller',
    place_id: 'ChIJaZhgmM3l3JQRlA7Kfs5hzRo',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Cândido de Abreu, 127 - Centro Cívico, Curitiba - PR, 80530-000, Brazil',
    cidade: 'Curitiba',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-050',
    nome: 'Bourbon Hypermarket',
    place_id: 'ChIJW6kGI1NCGZUR1aHu-TgchJY',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'R. Primeiro de Março, 1111 - Pátria Nova, Novo Hamburgo - RS, 93320-010, Brazil',
    cidade: 'Novo Hamburgo',
    time: 'SULcesso',
  },
  {
    id: 'loja-051',
    nome: 'ViaShopping',
    place_id: 'ChIJ5UXz9Qm-pgARoxzP9oGx55U',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Afonso Vaz de Melo, 640 - Barreiro, Belo Horizonte - MG, 30640-070, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-052',
    nome: 'RioMar Shopping Aracaju',
    place_id: 'ChIJw1YAg622GgcRrvmsGOHc3AA',
    estado: 'SE',
    regiao: 'Nordeste',
    endereco: 'Av. Delmiro Gouveia, 400 - Coroa do Meio, Aracaju - SE, 49035-500, Brazil',
    cidade: 'Aracajú',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-053',
    nome: 'Bauru Shopping',
    place_id: 'ChIJYcXLrGdnv5QR1iOlGAXDNJo',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Henrique Savi, 15 - 55 - Vila Nova Cidade Universitaria, Bauru - SP, 17011-900, Brazil',
    cidade: 'Bauru',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-054',
    nome: 'Center Shopping Uberlândia',
    place_id: 'ChIJC6hfUKJFpJQR3V3RU2DYJNY',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. João Naves de Ávila, 1331 - Tibery, Uberlândia - MG, 38408-902, Brazil',
    cidade: 'Uberlândia',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-055',
    nome: 'Garten Shopping',
    place_id: 'ChIJd8e8xaSv3pQR9HjkC2CM6Tg',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'Av. Rolf Wiest, 333 - Bom Retiro, Joinville - SC, 89223-005, Brazil',
    cidade: 'Joinville',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-056',
    nome: 'Boulevard Shopping Belo Horizonte',
    place_id: 'ChIJD9ag9IOZpgAR6vZX26nqLJ0',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. dos Andradas, 3000 - Santa Efigênia, Belo Horizonte - MG, 30260-070, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-057',
    nome: 'Rio Anil',
    place_id: 'ChIJgQaJnWCO9gcRXbWlhjd6UKw',
    estado: 'MA',
    regiao: 'Nordeste',
    endereco: 'Rio Anil, Maranhão, Brazil',
    cidade: 'São Luís',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-058',
    nome: 'Capim Dourado Shopping',
    place_id: 'ChIJCXNQqLzLJJMRQYgThVcwAzc',
    estado: 'TO',
    regiao: 'Norte',
    endereco: 'Q. 107 Norte Avenida NS 5, s/n - Plano Diretor Norte, Palmas - TO, 77001-098, Brazil',
    cidade: 'Palmas',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-059',
    nome: 'São Gonçalo Shopping',
    place_id: 'ChIJZQhZ4mabmQARovXp9rnBjNU',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Rod. Niterói - Manilha, 100 - Boa Vista, São Gonçalo - RJ, 24466-970, Brazil',
    cidade: 'São Gonçalo',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-060',
    nome: 'Catuaí Maringá Mall',
    place_id: 'ChIJt3pFWfvW7JQRBDCzmw95Ta4',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Colombo, 9161 - Parque Industrial Bandeirantes, Maringá - PR, 87070-000, Brazil',
    cidade: 'Maringá',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-061',
    nome: 'Shopping Norte Sul Plaza',
    place_id: 'ChIJ45hCLwzmhpQRzdjJy8hnOR4',
    estado: 'MS',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Presidente Ernesto Geisel, 2300 - Jardim Joquei Club, Campo Grande - MS, 79005-471, Brazil',
    cidade: 'Campo Grande',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-062',
    nome: 'West Shopping',
    place_id: 'ChIJfQUMCtLjmwARz_VW5-kkrzc',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Estr. do Mendanha, 555 - Campo Grande, Rio de Janeiro - RJ, 23087-283, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-063',
    nome: 'Salvador Norte Shopping',
    place_id: 'ChIJf_8cS3MaFgcRK37srcvNxkM',
    estado: 'BA',
    regiao: 'Nordeste',
    endereco: 'BA-526, 305 - São Cristóvão, Salvador - BA, 41510-000, Brazil',
    cidade: 'Salvador',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-064',
    nome: 'Minas Shopping',
    place_id: 'ChIJvzp-64qapgARyLE-xnHXmn0',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Cristiano Machado, 4000 - União, Belo Horizonte - MG, 31160-342, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-065',
    nome: 'Partage São Gonçalo',
    place_id: 'ChIJGY2h7OOamQARRoqCRJ8iEoY',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Pres. Kennedy, 425 - Centro, São Gonçalo - RJ, 24445-000, Brazil',
    cidade: 'São Gonçalo',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-066',
    nome: 'Polo Shopping Indaiatuba',
    place_id: 'ChIJz-JmGJ9Mz5QRKjSEPNJLE5o',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Alameda Filtros Mann, 670 - Jardim Tropical, Indaiatuba - SP, 13344-580, Brazil',
    cidade: 'Indaiatuba',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-067',
    nome: 'Norte Shopping',
    place_id: 'ChIJvxeEqtcd35QRFHJvRiUrqfs',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'Rodovia - BR-470, 3000 - Salto Norte, Blumenau - SC, 89065-800, Brazil',
    cidade: 'Blumenau',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-068',
    nome: 'Shopping PátioMix Resende',
    place_id: 'ChIJVcTAon9-ngAR3_jtLV9JbtQ',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Dorival Marcondes de Godoy - Fazenda do Castelo, Resende - RJ, 27535-320, Brazil',
    cidade: 'Resende',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-069',
    nome: 'Uberlândia Shopping',
    place_id: 'ChIJbaao6CpFpJQRxCovwUogXHo',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Paulo Gracindo, 15 - Morada da Colina, Uberlândia - MG, 38411-145, Brazil',
    cidade: 'Uberlândia',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-070',
    nome: 'Shopping da Ilha',
    place_id: 'ChIJp9b1WCSO9gcRfrqopQWqASA',
    estado: 'MA',
    regiao: 'Nordeste',
    endereco: 'Av. Daniel de La Touche, 987 - Cohama, São Luís - MA, 65061-901, Brazil',
    cidade: 'São Luís',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-071',
    nome: 'Parque Municipal Dom José - Barueri',
    place_id: 'ChIJv7npCbgDz5QRj-iOCyGLDpo',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Rua Ângela Mirella, 500 - Jardim Maria Tereza, Barueri - SP, 06411-330, Brazil',
    cidade: 'Barueri',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-072',
    nome: 'Park Shopping São Caetano',
    place_id: 'ChIJM-6NyJJczpQRO-orUUdtExI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Alameda Terracota, 545 - Cerâmica, São Caetano do Sul - SP, 09531-190, Brazil',
    cidade: 'São Caetano do Sul',
    time: 'Lobos SP',
  },
  {
    id: 'loja-073',
    nome: 'Golden Square Shopping',
    place_id: 'ChIJCTnNjLJDzpQRwvfS-MaAqXc',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Kennedy, 700 - Jardim do Mar, São Bernardo do Campo - SP, 09726-253, Brazil',
    cidade: 'São Bernardo do Campo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-074',
    nome: 'Pátio Limeira Shopping',
    place_id: 'ChIJiZFSCeuByJQRT-Z_vtLTFS4',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Carlos Gomes, 1321 - Centro, Limeira - SP, 13480-013, Brazil',
    cidade: 'Limeira',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-075',
    nome: 'Plaza Shopping Itu',
    place_id: 'ChIJdx6dhPBPz5QRj_4Pb485c38',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dr. Ermelindo Maffei, 1199 - Jardim Paraiso, Itu - SP, 13302-231, Brazil',
    cidade: 'Itú',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-076',
    nome: 'Shopping Campo Grande',
    place_id: 'ChIJDbHASpXohpQRuIhWy6CrSXE',
    estado: 'MS',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Afonso Pena, 4909 - Santa Fe, Campo Grande - MS, 79031-900, Brazil',
    cidade: 'Campo Grande',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-077',
    nome: 'Plaza Shopping',
    place_id: 'ChIJR6tIJ9uDmQARYDz2YyfeSSE',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Rua Quinze de Novembro, 8 - Centro, Niterói - RJ, 24020-125, Brazil',
    cidade: 'Niterói',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-078',
    nome: 'River Shopping Mall',
    place_id: 'ChIJV1pERmtwcwcRYnuYVkUP4iI',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'Av. Monsenhor Ângelo Sampaio, nº 100 - Centro, Petrolina - PE, 56304-920, Brazil',
    cidade: 'Petrolina',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-079',
    nome: 'Pátio Shopping Chapecó',
    place_id: 'ChIJq6qqWpe25JQRSttt1B8qGkU',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'Av. Fernando Machado, 4000 D - Líder, Chapecó - SC, 89805-203, Brazil',
    cidade: 'Chapecó',
    time: 'SULcesso',
  },
  {
    id: 'loja-080',
    nome: 'Shopping Sul',
    place_id: 'ChIJh5LGS6CGWZMR5e3aos4u9i0',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'BR-040 - Parque Esplanada III, Valparaíso de Goiás - GO, 72876-902, Brazil',
    cidade: 'Valparaíso de Goiás',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-081',
    nome: 'Palladium Shopping Center Ponta Grossa',
    place_id: 'ChIJkXWL2UUa6JQRTvlJP5wXMrI',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'R. Ermelino de Leão, 703 - Olarias, Ponta Grossa - PR, 84035-903, Brazil',
    cidade: 'Ponta Grossa',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-082',
    nome: 'Manauara Shopping',
    place_id: 'ChIJDd25ilAFbJIRno-xEMovwo8',
    estado: 'AM',
    regiao: 'Norte',
    endereco: 'Av. Mário Ypiranga, 1300 - Adrianópolis, Manaus - AM, 69053-165, Brazil',
    cidade: 'Manaus',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-083',
    nome: 'International Mall',
    place_id: 'ChIJVVVVVYBfzpQRY1xWFynXT24',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Rod. Pres. Dutra, 225 - Vila Itapegica, Guarulhos - SP, 07034-911, Brazil',
    cidade: 'Guarulhos',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-084',
    nome: 'Parque Shopping Belém',
    place_id: 'ChIJm0fBs9dhpJIRTUANRNfFdHI',
    estado: 'PA',
    regiao: 'Norte',
    endereco: 'Rod. Augusto Montenegro, 4300 - Parque Verde, Belém - PA, 66635-110, Brazil',
    cidade: 'Belém',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-085',
    nome: 'Shopping Bela Vista',
    place_id: 'ChIJ0Zdy3dkaFgcRqzWIKS9USSQ',
    estado: 'BA',
    regiao: 'Nordeste',
    endereco: 'Alameda Euvaldo Luz, 92 - Horto Bela Vista, Salvador - BA, 41098-020, Brazil',
    cidade: 'Salvador',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-086',
    nome: 'Shopping Parque das Bandeiras',
    place_id: 'ChIJ60uXehrIyJQR-_ZLwTJcOwI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. John Boyd Dunlop, 3900 - Jardim Ipaussurama, Campinas - SP, 13060-803, Brazil',
    cidade: 'Campinas',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-087',
    nome: 'Jundiaí Shopping',
    place_id: 'ChIJs8PUSLwmz5QRwrYiGpn2CWE',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. 9 de Julho, 3333 - Anhangabaú, Jundiaí - SP, 13208-056, Brazil',
    cidade: 'Jundiaí',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-088',
    nome: 'Grand Plaza Shopping',
    place_id: 'ChIJB2Nn_5RCzpQRWob_OIIau9k',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Industrial, 600 - Jardim, Santo André - SP, 09080-510, Brazil',
    cidade: 'Santo André',
    time: 'Lobos SP',
  },
  {
    id: 'loja-089',
    nome: 'Shopping Pátio Batel',
    place_id: 'ChIJVTrD6I7j3JQRpoHwWtYxX0k',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. do Batel, 1868 - Batel, Curitiba - PR, 80420-090, Brazil',
    cidade: 'Curitiba',
    time: 'Ultra High',
  },
  {
    id: 'loja-090',
    nome: 'RioMar Recife',
    place_id: 'ChIJRXxg7DsfqwcRTWwjGuZLtPk',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'Av. República do Líbano, 251 - Pina, Recife - PE, 51110-160, Brazil',
    cidade: 'Recife',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-091',
    nome: 'Shopping Estação BH',
    place_id: 'ChIJjwgFVvaPpgARxkTriIdETSo',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Cristiano Machado, 11833 - Vila Cloris, Belo Horizonte - MG, 31744-007, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-092',
    nome: 'Continente Shopping',
    place_id: 'ChIJv3kvQ_s1J5URbmzITC7USpw',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'Esquina Rod - BR-101, KM 210 - Distrito Industrial, São José - SC, 88104-800, Brazil',
    cidade: 'São José',
    time: 'SULcesso',
  },
  {
    id: 'loja-093',
    nome: 'Boulevard Shopping Londrina',
    place_id: 'ChIJQQ5FxHxD65QRfq4dkbxEBu0',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Theodoro Victorelli, 150 - Carlota, Londrina - PR, 86027-750, Brazil',
    cidade: 'Londrina',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-094',
    nome: 'Mogi Shopping',
    place_id: 'ChIJ4c35qTbYzZQRerfedzu3fyI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Ver. Narciso Yague Guimarães, 1001 - Jardim Armenia, Mogi das Cruzes - SP, 08780-000, Brazil',
    cidade: 'Mogi das Cruzes',
    time: 'Falcões SP',
  },
  {
    id: 'loja-095',
    nome: 'São Bernardo Plaza Shopping',
    place_id: 'ChIJ2QEABZdBzpQRH1Prw3-FlAM',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Rotary, 624 - Centro, São Bernardo do Campo - SP, 09721-000, Brazil',
    cidade: 'São Bernardo do Campo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-096',
    nome: 'Amazonas Shopping Center',
    place_id: 'ChIJQcmFCp0abJIRFSNJC3oNLxs',
    estado: 'AM',
    regiao: 'Norte',
    endereco: 'Av. Djalma Batista, 482 - Parque 10 de Novembro, Manaus - AM, 69050-010, Brazil',
    cidade: 'Manaus',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-097',
    nome: 'Shopping Pelotas',
    place_id: 'ChIJ8Z3msY9ZzpQRuP2v3JPYvk4',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. Ferreira Viana, 1526 - Areal, Pelotas - RS, 96085-000, Brazil',
    cidade: 'Pelotas',
    time: 'SULcesso',
  },
  {
    id: 'loja-098',
    nome: 'Tiete Plaza Shopping Mall',
    place_id: 'ChIJyzfO-7r7zpQRTLJBfQu5zG0',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Raimundo Pereira de Magalhães, 1465 - Jardim Iris, São Paulo - SP, 05145-000, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-099',
    nome: 'Natal Shopping',
    place_id: 'ChIJj2AvPX__sgcRNr1SxD-1jdU',
    estado: 'RN',
    regiao: 'Nordeste',
    endereco: 'Avenida Senador Salgado Filho, 2234 - Av. das Brancas Dunas, 47 - Candelária, Natal - RN, 59064-900, Brazil',
    cidade: 'Natal',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-100',
    nome: 'Arapiraca Garden Shopping',
    place_id: 'ChIJ17WYXInVBQcRkEuM4g_V-io',
    estado: 'AL',
    regiao: 'Nordeste',
    endereco: 'R. José Jaílson Nunes, 493 - Santa Edwiges, Arapiraca - AL, 57310-400, Brazil',
    cidade: 'Arapiraca',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-101',
    nome: 'Shopping Metropolitano Barra',
    place_id: 'ChIJXZaz-wPZmwARbjbMeUFG1Mg',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Embaixador Abelardo Bueno, 1300 - Barra Olímpica, Rio de Janeiro - RJ, 22775-040, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-102',
    nome: 'Parque Shopping Maceió',
    place_id: 'ChIJs880fdVFAQcRDJ85vbEBgSg',
    estado: 'AL',
    regiao: 'Nordeste',
    endereco: 'Av. Comendador Gustavo Paiva, 5945 - Cruz das Almas, Maceió - AL, 57038-000, Brazil',
    cidade: 'Maceió',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-103',
    nome: 'Shopping RioMar Fortaleza',
    place_id: 'ChIJE4p28jFGxwcRA44wuYTz488',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'R. Des. Lauro Nogueira, 1500 - Papicu, Fortaleza - CE, 60175-055, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-104',
    nome: 'Campinas Shopping',
    place_id: 'ChIJb3Fzl9_IyJQRjTD2JBoItMY',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Jacy Teixeira de Camargo, 940 - Jardim do Lago, Campinas - SP, 13050-913, Brazil',
    cidade: 'Campinas',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-105',
    nome: 'Pantanal Shopping',
    place_id: 'ChIJ9z0tCv2wnZMRKRx3XTv0LI0',
    estado: 'MT',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Historiador Rubens de Mendonça, 3300 - Jardim Aclimacao, Cuiabá - MT, 78020-250, Brazil',
    cidade: 'Cuiabá',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-106',
    nome: 'Shopping RioMar Kennedy',
    place_id: 'ChIJJXrsG4dJxwcRXyolQMKLavY',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'Av. Srg. Hermínio Sampaio, 3100 - Presidente Kennedy, Fortaleza - CE, 60355-512, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-107',
    nome: 'Park Shopping Canoas',
    place_id: 'ChIJ09RkPBFwGZURz1gmxlFbvxY',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. Farroupilha, 4545 - Mal. Rondon, Canoas - RS, 92020-475, Brazil',
    cidade: 'Canoas',
    time: 'SULcesso',
  },
  {
    id: 'loja-108',
    nome: 'Shopping Estação Cuiabá.',
    place_id: 'ChIJBR0EZymynZMRi1jcaBVF59c',
    estado: 'MT',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Miguel Sutil, 9300 - Santa Rosa, Cuiabá - MT, 78040-365, Brazil',
    cidade: 'Cuiabá',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-109',
    nome: 'Shopping Iguatemi Porto Alegre',
    place_id: 'ChIJk5ltpp53GZURYk9cuiHLd5Q',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. João Wallig, 1800 - Passo d\'Areia, Porto Alegre - RS, 91349-900, Brazil',
    cidade: 'Porto Alegre',
    time: 'SULcesso',
  },
  {
    id: 'loja-110',
    nome: 'BarraShoppingSul',
    place_id: 'ChIJuxnD0tJ5GZURUjsNbS4BTWM',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. Diário de Notícias, 300 - Cristal, Porto Alegre - RS, 90810-080, Brazil',
    cidade: 'Porto Alegre',
    time: 'SULcesso',
  },
  {
    id: 'loja-111',
    nome: 'Barra Shopping',
    place_id: 'ChIJtfU8L0jamwARvyjdP06T3ac',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. das Américas, 4666 - Barra da Tijuca, Rio de Janeiro - RJ, 22640-102, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-112',
    nome: 'Jockey Plaza Shopping',
    place_id: 'ChIJU8Be6ozl3JQRwnQ1ITwZI1M',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'R. Konrad Adenauer, 370 - Tarumã, Curitiba - PR, 82821-020, Brazil',
    cidade: 'Curitiba',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-113',
    nome: 'North Shopping Jóquei',
    place_id: 'ChIJteQdKPlLxwcRhQv-hQqtvL8',
    estado: 'CE',
    regiao: 'Nordeste',
    endereco: 'Av. Lineu Machado, 419 - Jóquei Clube, Fortaleza - CE, 60520-102, Brazil',
    cidade: 'Fortaleza',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-114',
    nome: 'Carioca Shopping',
    place_id: 'ChIJebY-kJh8mQARjRL5wRPl8EU',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Vicente de Carvalho, 909 - Vila da Penha, Rio de Janeiro - RJ, 21210-000, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-115',
    nome: 'Américas Shopping',
    place_id: 'ChIJlQ9EZjfdmwAR2zphCAuLVEE',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. das Américas, 15500 - Recreio dos Bandeirantes, Rio de Janeiro - RJ, 22790-702, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Esquadrão 40 graus',
  },
  {
    id: 'loja-116',
    nome: 'Pátio Belém Mall',
    place_id: 'ChIJF_QTmouOpJIR3uNx-MHUWzw',
    estado: 'PA',
    regiao: 'Norte',
    endereco: 'Tv. Padre Eutíquio, 1078 - Batista Campos, Belém - PA, 66023-710, Brazil',
    cidade: 'Belém',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-117',
    nome: 'Shopping Bosque Grão-Pará',
    place_id: 'ChIJ-ex1NyxgpJIR50HdZs-7yXw',
    estado: 'PA',
    regiao: 'Norte',
    endereco: 'Av. Centenário, 1052 - Val-de-Cans, Belém - PA, 66640-150, Brazil',
    cidade: 'Belém',
    time: 'Flechas do Norte',
  },
  {
    id: 'loja-118',
    nome: 'Shopping Bosque dos Ipês',
    place_id: 'ChIJB2VbctHphpQRcGH3pHE1P6s',
    estado: 'MS',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Cônsul Assaf Trad, 4796 - Parque dos Novos Estados, Campo Grande - MS, 79035-900, Brazil',
    cidade: 'Campo Grande',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-119',
    nome: 'Bosque Maia',
    place_id: 'ChIJm_NtXj_1zpQRWxkd8WuLh_4',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Paulo Faccini, s/n - Centro, Guarulhos - SP, 07115-260, Brazil',
    cidade: 'Guarulhos',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-120',
    nome: 'Parque Shopping Bahia',
    place_id: 'ChIJbSLdgTUXFgcRlrjA7LblyoI',
    estado: 'BA',
    regiao: 'Nordeste',
    endereco: 'Av. Santos Dumont, 4360 - Centro, Lauro de Freitas - BA, 42702-400, Brazil',
    cidade: 'Lauro de Freitas',
    time: 'Esquadrão Valente',
  },
  {
    id: 'loja-121',
    nome: 'Boulevard Shopping Bauru',
    place_id: 'ChIJJ-O0_Ltnv5QR3UpohSMGsF4',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'R. Marcondes Salgado, Quadra 11 - Chácara das Flores, Bauru - SP, 17013-113, Brazil',
    cidade: 'Bauru',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-122',
    nome: 'Avenida Paulista',
    place_id: 'ChIJFaMK2shZzpQRanfJ8jGUn9U',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Paulista, São Paulo - SP, Brazil',
    cidade: 'São Paulo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-123',
    nome: 'Partage Rio Grande',
    place_id: 'ChIJD2S73buaEZUR5Dl4JLgT2-4',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. Engenheira Lúcia Maria Balbela Chiesa, 2842 - Parque Res. Sao Pedro, Rio Grande - RS, 96216-400, Brazil',
    cidade: 'Rio Grande',
    time: 'SULcesso',
  },
  {
    id: 'loja-124',
    nome: 'Shopping Itaguaçu',
    place_id: 'ChIJ-7z9VdtJJ5URe4BqaRCDUIo',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'R. Gerôncio Thives, 1079 - Barreiros, São José - SC, 88117-900, Brazil',
    cidade: 'São José',
    time: 'SULcesso',
  },
  {
    id: 'loja-125',
    nome: 'Passeio das Águas Shopping',
    place_id: 'ChIJg57ZEGXzXpMRutGR1cz0vyk',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Perimetral Norte, 8303 - Fazenda Caveiras, Goiânia - GO, 74573-260, Brazil',
    cidade: 'Goiânia',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-126',
    nome: 'Shopping Rio Poty',
    place_id: 'ChIJc2l6Wuk5jgcR6mgkKF4g87k',
    estado: 'PI',
    regiao: 'Nordeste',
    endereco: 'Av. Mar. Castelo Branco, 911 - Porenquanto, Teresina - PI, 64003-087, Brazil',
    cidade: 'Teresina',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-127',
    nome: 'Shopping Iguatemi São José do Rio Preto',
    place_id: 'ChIJmf9SXHazvZQRzf0QRRqvFt8',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Pres. Juscelino K. de Oliveira, 5000 - Iguatemi, São José do Rio Preto - SP, 15093-340, Brazil',
    cidade: 'São José do Rio Preto',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-128',
    nome: 'Shopping Iguatemi Campinas',
    place_id: 'ChIJ4Wxq0XPPyJQR4RvPLfbSyfY',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Iguatemi, 777 - Vila Brandina, Campinas - SP, 13092-902, Brazil',
    cidade: 'Campinas',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-129',
    nome: 'Flamboyant Shopping Center',
    place_id: 'ChIJx2LOj532XpMRErHmTjPOk3s',
    estado: 'GO',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Dep. Jamel Cecílio, 3300 - Jardim Goiás, Goiânia - GO, 74810-907, Brazil',
    cidade: 'Goiânia',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-130',
    nome: 'Shopping Del Rey',
    place_id: 'ChIJJ9U5gsOZpgARm7XyElrYV90',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Av. Presidente Carlos Luz, 3001 - Pampulha, Belo Horizonte - MG, 31250-010, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-131',
    nome: 'Pátio Cianê Shopping',
    place_id: 'ChIJgToQL6WKxZQRVSL_zt2v6o0',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dr. Afonso Vergueiro, 823 - Centro, Sorocaba - SP, 18035-370, Brazil',
    cidade: 'Sorocaba',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-132',
    nome: 'TriMais Supermercado - Lauzane Paulista',
    place_id: 'ChIJLesa_2P3zpQRiudyNmzvh6A',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dr. Francisco Ranieri, 834 - Lauzane Paulista, São Paulo - SP, 02435-061, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-133',
    nome: 'Maringá Park Shopping Center',
    place_id: 'ChIJcUE0tdPQ7JQR6uIthPLq13o',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. São Paulo, 1099 - Zona 01, Maringá - PR, 87013-040, Brazil',
    cidade: 'Maringá',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-134',
    nome: 'Serra da Cantareira',
    place_id: 'ChIJjwwF8FDxzpQRnSm9DT79DII',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Serra da Cantareira - Sítio Barrocada, São Paulo - State of São Paulo, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-135',
    nome: 'Shopping Iguatemi Porto Alegre',
    place_id: 'ChIJk5ltpp53GZURYk9cuiHLd5Q',
    estado: 'RS',
    regiao: 'Sul',
    endereco: 'Av. João Wallig, 1800 - Passo d\'Areia, Porto Alegre - RS, 91349-900, Brazil',
    cidade: 'Porto Alegre',
    time: 'SULcesso',
  },
  {
    id: 'loja-136',
    nome: 'Shopping Iguatemi Brasília',
    place_id: 'ChIJ9Y8QHpswWpMRzohd-1XpYt0',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'SHIN CA 4 - Lago Norte, Brasília - DF, 71503-504, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-137',
    nome: 'Shopping Iguatemi Ribeirão Preto',
    place_id: 'ChIJv3rQSZu5uZQRWZ90ZPh2Bfs',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Luiz Eduardo Toledo Prado, 900 - Vila do Golfe, Ribeirão Preto - SP, 14027-250, Brazil',
    cidade: 'Ribeirão Preto',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-138',
    nome: 'Shopping Palladium Umuarama',
    place_id: 'ChIJv_qNTX3R8pQRz8otWLH7t6E',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Paraná, 8455 - Parque Industrial II, Umuarama - PR, 87502-000, Brazil',
    cidade: 'Umuarama',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-139',
    nome: 'Patteo Olinda Shopping',
    place_id: 'ChIJgz0bf0c9qwcRKG631z4p-Jo',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'R. Carmelita Muniz de Araújo, 225 - Casa Caiada, Olinda - PE, 53130-645, Brazil',
    cidade: 'Olinda',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-140',
    nome: 'JK Iguatemi',
    place_id: 'ChIJE41U01hXzpQRxegWeO3ssok',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Pres. Juscelino Kubitschek, 2041 - Vila Olímpia, São Paulo - SP, 04543-011, Brazil',
    cidade: 'São Paulo',
    time: 'Ultra High',
  },
  {
    id: 'loja-141',
    nome: 'Iguatemi Shopping',
    place_id: 'ChIJtb39eG1XzpQRrsiFJG_8XwA',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Brig. Faria Lima, 2232 - Jardim Paulistano, São Paulo - SP, 01451-000, Brazil',
    cidade: 'São Paulo',
    time: 'Ultra High',
  },
  {
    id: 'loja-142',
    nome: 'Shopping Sinop',
    place_id: 'ChIJ59J5QFjVCZMRTN2tRilABQE',
    estado: 'MT',
    regiao: 'Centro-Oeste',
    endereco: 'Av. Alexandre Ferronato, 800 - St. Industrial, Sinop - MT, 78557-247, Brazil',
    cidade: 'Sinop',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-143',
    nome: 'Shopping Praça Nova Araçatuba',
    place_id: 'ChIJZXUv-YJDlpQRUPk25kP-Y6g',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Rua Carlos Pereira da Silva, 6000 - Jardim Guanabara, Araçatuba - SP, 16026-035, Brazil',
    cidade: 'Araçatuba',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-144',
    nome: 'Tucuruvi',
    place_id: 'ChIJ03T7TW32zpQRGUmE0Q9VBcI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Dr. Antônio Maria Laet, 100 - Tucuruvi, São Paulo - SP, 02240-000, Brazil',
    cidade: 'São Paulo',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-145',
    nome: 'Shopping Conjunto Nacional',
    place_id: 'ChIJ85luKjw7WpMR4Yfm6hmdYII',
    estado: 'DF',
    regiao: 'Centro-Oeste',
    endereco: 'SDN, CNB - Asa Norte, Brasília - DF, 70077-900, Brazil',
    cidade: 'Brasília',
    time: 'Águias do Cerrado',
  },
  {
    id: 'loja-146',
    nome: 'Shopping Curitiba',
    place_id: 'ChIJRyOy8HDk3JQREPun8P4ZqYk',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'R. Brig. Franco, 2300 - Centro, Curitiba - PR, 80250-030, Brazil',
    cidade: 'Curitiba',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-147',
    nome: 'Shopping Pátio Maceió',
    place_id: 'ChIJ9a-eQBdIAQcRHr8QcRDyw4s',
    estado: 'AL',
    regiao: 'Nordeste',
    endereco: 'Av. Menino Marcelo, 3800 - Cidade Universitária, Maceió - AL, 57073-900, Brazil',
    cidade: 'Maceió',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-148',
    nome: 'Shopping Nova América',
    place_id: 'ChIJaUUM6Bh9mQAR5Q272qHVK8Y',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Av. Pastor Martin Luther King Jr., 126 - Del Castilho, Rio de Janeiro - RJ, 20765-000, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-149',
    nome: 'Madureira Shopping',
    place_id: 'ChIJoRufyCljmQARzoB1XvDtk7g',
    estado: 'RJ',
    regiao: 'Sudeste',
    endereco: 'Estr. do Portela, 222 - Madureira, Rio de Janeiro - RJ, 21351-050, Brazil',
    cidade: 'Rio de Janeiro',
    time: 'Águias de Elite',
  },
  {
    id: 'loja-150',
    nome: 'Iguatemi Alphaville Shopping Mall',
    place_id: 'ChIJKdzx_CACz5QR6TTipHDvhDs',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Al. Rio Negro, 111 - Alphaville Industrial, Barueri - SP, 06454-000, Brazil',
    cidade: 'Barueri',
    time: 'Gigante Paulista',
  },
  {
    id: 'loja-151',
    nome: 'Shopping Mueller',
    place_id: 'ChIJ7ygr30ew3pQRHak1J2gI8gs',
    estado: 'SC',
    regiao: 'Sul',
    endereco: 'R. Visc. de Taunay, 235 - Centro - Centro, Joinville - SC, 89201-420, Brazil',
    cidade: 'Joinville',
    time: 'Furacão Sul I',
  },
  {
    id: 'loja-152',
    nome: 'Vale Sul Shopping',
    place_id: 'ChIJkYpfvYhKzJQR4iLPekMTZJI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Andrômeda, 227 - Jardim Satélite, São José dos Campos - SP, 12230-000, Brazil',
    cidade: 'São Paulo',
    time: 'Falcões SP',
  },
  {
    id: 'loja-153',
    nome: 'Plaza Sul Shopping',
    place_id: 'ChIJRePahalbzpQRYDVy_OoiwcI',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Praça Leonor Kaupa, 100 - LOJA EUC 172/173 - Jardim da Saúde, São Paulo - SP, 04151-100, Brazil',
    cidade: 'São Paulo',
    time: 'Lobos SP',
  },
  {
    id: 'loja-154',
    nome: 'Rio Preto Shopping',
    place_id: 'ChIJNROHavayvZQRPFclp4c7yBA',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Brg. Faria Lima, 6363 - Jardim Morumbi, São José do Rio Preto - SP, 15090-900, Brazil',
    cidade: 'São José do Rio Preto',
    time: 'Guadiões da Fronteira',
  },
  {
    id: 'loja-155',
    nome: 'Shopping Cidade',
    place_id: 'ChIJEVbOc-OZpgARJRTGYR-OaIA',
    estado: 'MG',
    regiao: 'Sudeste',
    endereco: 'Rua dos Tupis, 337 - Centro, Belo Horizonte - MG, 30190-060, Brazil',
    cidade: 'Belo Horizonte',
    time: 'Legião Mineira',
  },
  {
    id: 'loja-156',
    nome: 'Maxi Shopping',
    place_id: 'ChIJ8WXRH2Umz5QRtGUOFhAQU8Q',
    estado: 'SP',
    regiao: 'Sudeste',
    endereco: 'Av. Antônio Frederico Ozanan, 6000 - Vila Rio Branco, Jundiaí - SP, 13215-900, Brazil',
    cidade: 'Jundiaí',
    time: 'Fúria do Interior',
  },
  {
    id: 'loja-157',
    nome: 'Caruaru Shopping',
    place_id: 'ChIJsaQX2laKqQcRVyKFcJYJsog',
    estado: 'PE',
    regiao: 'Nordeste',
    endereco: 'Av. Adjar da Silva Casé, 800 - Indianópolis, Caruaru - PE, 55024-740, Brazil',
    cidade: 'Caruaru',
    time: 'Guerreiros do Cangaço',
  },
  {
    id: 'loja-158',
    nome: 'Catuaí Shopping Cascavel',
    place_id: 'ChIJ_YJGZOvV85QRJHuUx27lJoU',
    estado: 'PR',
    regiao: 'Sul',
    endereco: 'Av. Brasil, 3545 - Região do Lago, Cascavel - PR, 85812-500, Brazil',
    cidade: 'Cascavel',
    time: 'Furacão Sul I',
  },
];

